#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR" || exit

mkdir -p bin
go build -o bin/kauma main/main.go

mkdir -p /dut
cp bin/kauma /dut/kauma
cp bin/kauma ./kauma
cp "bin/kauma" "$SCRIPT_DIR/kauma"