name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and analyze Go project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.17'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run Go tests and generate coverage
        run: go test -coverprofile=coverage.out ./...

      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.coverage.exclusions=**/test/**,**/vendor/**

      - name: Check the Quality Gate
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Fail if Quality Gate fails
        if: failure() && github.event_name == 'pull_request' && github.base_ref == 'main'
        run: exit 1
